/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSiswaExamsRouteImport } from './routes/_authenticated/siswa/exams'
import { Route as AuthenticatedGuruQuestionsRouteImport } from './routes/_authenticated/guru/questions'
import { Route as AuthenticatedGuruGradingRouteImport } from './routes/_authenticated/guru/grading'
import { Route as AuthenticatedGuruExamsRouteImport } from './routes/_authenticated/guru/exams'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedSiswaResultAttemptIdRouteImport } from './routes/_authenticated/siswa/result.$attemptId'
import { Route as AuthenticatedSiswaExamAttemptIdRouteImport } from './routes/_authenticated/siswa/exam.$attemptId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiswaExamsRoute = AuthenticatedSiswaExamsRouteImport.update({
  id: '/siswa/exams',
  path: '/siswa/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuruQuestionsRoute =
  AuthenticatedGuruQuestionsRouteImport.update({
    id: '/guru/questions',
    path: '/guru/questions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuruGradingRoute =
  AuthenticatedGuruGradingRouteImport.update({
    id: '/guru/grading',
    path: '/guru/grading',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuruExamsRoute = AuthenticatedGuruExamsRouteImport.update({
  id: '/guru/exams',
  path: '/guru/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/admin/subjects',
    path: '/admin/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiswaResultAttemptIdRoute =
  AuthenticatedSiswaResultAttemptIdRouteImport.update({
    id: '/siswa/result/$attemptId',
    path: '/siswa/result/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiswaExamAttemptIdRoute =
  AuthenticatedSiswaExamAttemptIdRouteImport.update({
    id: '/siswa/exam/$attemptId',
    path: '/siswa/exam/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/guru/exams': typeof AuthenticatedGuruExamsRoute
  '/guru/grading': typeof AuthenticatedGuruGradingRoute
  '/guru/questions': typeof AuthenticatedGuruQuestionsRoute
  '/siswa/exams': typeof AuthenticatedSiswaExamsRoute
  '/siswa/exam/$attemptId': typeof AuthenticatedSiswaExamAttemptIdRoute
  '/siswa/result/$attemptId': typeof AuthenticatedSiswaResultAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/guru/exams': typeof AuthenticatedGuruExamsRoute
  '/guru/grading': typeof AuthenticatedGuruGradingRoute
  '/guru/questions': typeof AuthenticatedGuruQuestionsRoute
  '/siswa/exams': typeof AuthenticatedSiswaExamsRoute
  '/siswa/exam/$attemptId': typeof AuthenticatedSiswaExamAttemptIdRoute
  '/siswa/result/$attemptId': typeof AuthenticatedSiswaResultAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/guru/exams': typeof AuthenticatedGuruExamsRoute
  '/_authenticated/guru/grading': typeof AuthenticatedGuruGradingRoute
  '/_authenticated/guru/questions': typeof AuthenticatedGuruQuestionsRoute
  '/_authenticated/siswa/exams': typeof AuthenticatedSiswaExamsRoute
  '/_authenticated/siswa/exam/$attemptId': typeof AuthenticatedSiswaExamAttemptIdRoute
  '/_authenticated/siswa/result/$attemptId': typeof AuthenticatedSiswaResultAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/subjects'
    | '/admin/users'
    | '/guru/exams'
    | '/guru/grading'
    | '/guru/questions'
    | '/siswa/exams'
    | '/siswa/exam/$attemptId'
    | '/siswa/result/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/subjects'
    | '/admin/users'
    | '/guru/exams'
    | '/guru/grading'
    | '/guru/questions'
    | '/siswa/exams'
    | '/siswa/exam/$attemptId'
    | '/siswa/result/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/users'
    | '/_authenticated/guru/exams'
    | '/_authenticated/guru/grading'
    | '/_authenticated/guru/questions'
    | '/_authenticated/siswa/exams'
    | '/_authenticated/siswa/exam/$attemptId'
    | '/_authenticated/siswa/result/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siswa/exams': {
      id: '/_authenticated/siswa/exams'
      path: '/siswa/exams'
      fullPath: '/siswa/exams'
      preLoaderRoute: typeof AuthenticatedSiswaExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/questions': {
      id: '/_authenticated/guru/questions'
      path: '/guru/questions'
      fullPath: '/guru/questions'
      preLoaderRoute: typeof AuthenticatedGuruQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/grading': {
      id: '/_authenticated/guru/grading'
      path: '/guru/grading'
      fullPath: '/guru/grading'
      preLoaderRoute: typeof AuthenticatedGuruGradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/exams': {
      id: '/_authenticated/guru/exams'
      path: '/guru/exams'
      fullPath: '/guru/exams'
      preLoaderRoute: typeof AuthenticatedGuruExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/admin/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siswa/result/$attemptId': {
      id: '/_authenticated/siswa/result/$attemptId'
      path: '/siswa/result/$attemptId'
      fullPath: '/siswa/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedSiswaResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siswa/exam/$attemptId': {
      id: '/_authenticated/siswa/exam/$attemptId'
      path: '/siswa/exam/$attemptId'
      fullPath: '/siswa/exam/$attemptId'
      preLoaderRoute: typeof AuthenticatedSiswaExamAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedGuruExamsRoute: typeof AuthenticatedGuruExamsRoute
  AuthenticatedGuruGradingRoute: typeof AuthenticatedGuruGradingRoute
  AuthenticatedGuruQuestionsRoute: typeof AuthenticatedGuruQuestionsRoute
  AuthenticatedSiswaExamsRoute: typeof AuthenticatedSiswaExamsRoute
  AuthenticatedSiswaExamAttemptIdRoute: typeof AuthenticatedSiswaExamAttemptIdRoute
  AuthenticatedSiswaResultAttemptIdRoute: typeof AuthenticatedSiswaResultAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedGuruExamsRoute: AuthenticatedGuruExamsRoute,
  AuthenticatedGuruGradingRoute: AuthenticatedGuruGradingRoute,
  AuthenticatedGuruQuestionsRoute: AuthenticatedGuruQuestionsRoute,
  AuthenticatedSiswaExamsRoute: AuthenticatedSiswaExamsRoute,
  AuthenticatedSiswaExamAttemptIdRoute: AuthenticatedSiswaExamAttemptIdRoute,
  AuthenticatedSiswaResultAttemptIdRoute:
    AuthenticatedSiswaResultAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
